"""Closed sets used across the opportunity lifecycle."""

from __future__ import annotations

from enum import StrEnum


class MechanismKind(StrEnum):
    STRUCTURAL_MECHANISM = "STRUCTURAL_MECHANISM"
    PATTERN = "PATTERN"
    TRADABLE_ALPHA = "TRADABLE_ALPHA"


class AlphaLifecycle(StrEnum):
    DISCOVERY = "DISCOVERY"
    VALIDATING = "VALIDATING"
    ACTIVE = "ACTIVE"
    DECAYING = "DECAYING"
    DORMANT = "DORMANT"
    RETIRED = "RETIRED"
    REJECTED = "REJECTED"


class OpportunityStatus(StrEnum):
    DISCOVERED = "DISCOVERED"
    WATCHING = "WATCHING"
    READY = "READY"
    ENTERED = "ENTERED"
    CONVERGING = "CONVERGING"
    EXIT_READY = "EXIT_READY"
    EXITED = "EXITED"
    INVALIDATED = "INVALIDATED"
    EXPIRED = "EXPIRED"
    REJECTED = "REJECTED"


class DecisionState(StrEnum):
    LONG = "LONG"
    SHORT = "SHORT"
    NO_TRADE = "NO_TRADE"
    WATCH = "WATCH"
    WAIT_PULLBACK = "WAIT_PULLBACK"
    WAIT_BREAKOUT = "WAIT_BREAKOUT"
    WAIT_CONFIRMATION = "WAIT_CONFIRMATION"
    MODEL_UNCERTAIN = "MODEL_UNCERTAIN"
    ALPHA_DECAYING = "ALPHA_DECAYING"
    DATA_DEGRADED = "DATA_DEGRADED"


class EntryStrategy(StrEnum):
    MARKET = "MARKET"
    LIMIT_PULLBACK = "LIMIT_PULLBACK"
    BREAKOUT_CONFIRMATION = "BREAKOUT_CONFIRMATION"
    WAIT = "WAIT"


class ExitReason(StrEnum):
    MISPRICING_CLOSED = "MISPRICING_CLOSED"
    THESIS_INVALIDATED = "THESIS_INVALIDATED"
    ALPHA_DECAYED = "ALPHA_DECAYED"
    TIME_EXPIRED = "TIME_EXPIRED"
    STOP_LOSS = "STOP_LOSS"
    TARGET_REACHED = "TARGET_REACHED"
    REGIME_CHANGE = "REGIME_CHANGE"
    LIQUIDITY_EVENT = "LIQUIDITY_EVENT"


class MispricingClass(StrEnum):
    POSSIBLE_MISPRICING = "POSSIBLE_MISPRICING"
    MODEL_ERROR = "MODEL_ERROR"
    REGIME_BREAK = "REGIME_BREAK"
    EVENT_DISLOCATION = "EVENT_DISLOCATION"
    LIQUIDITY_DISTORTION = "LIQUIDITY_DISTORTION"
    UNKNOWN = "UNKNOWN"


class RegimeName(StrEnum):
    POLICY_DIVERGENCE = "POLICY_DIVERGENCE"
    RATE_DIVERGENCE = "RATE_DIVERGENCE"
    GROWTH_DIVERGENCE = "GROWTH_DIVERGENCE"
    INFLATION_DIVERGENCE = "INFLATION_DIVERGENCE"
    CARRY = "CARRY"
    RISK_OFF = "RISK_OFF"
    TREND = "TREND"
    MEAN_REVERSION = "MEAN_REVERSION"
    LIQUIDITY_STRESS = "LIQUIDITY_STRESS"
    DISLOCATION = "DISLOCATION"
    NEUTRAL = "NEUTRAL"


class TradeReviewLabel(StrEnum):
    THESIS_CORRECT_EXECUTION_GOOD = "THESIS_CORRECT_EXECUTION_GOOD"
    THESIS_CORRECT_EXECUTION_BAD = "THESIS_CORRECT_EXECUTION_BAD"
    THESIS_WRONG = "THESIS_WRONG"
    MODEL_ERROR = "MODEL_ERROR"
    ALPHA_DECAY = "ALPHA_DECAY"
    REGIME_CHANGE = "REGIME_CHANGE"
    RANDOM_OUTCOME = "RANDOM_OUTCOME"


class ExperimentConclusion(StrEnum):
    PROMISING = "PROMISING"
    INCONCLUSIVE = "INCONCLUSIVE"
    REJECTED = "REJECTED"


class Direction(StrEnum):
    LONG = "LONG"
    SHORT = "SHORT"


class FillSide(StrEnum):
    BUY = "BUY"
    SELL = "SELL"


class SpreadSource(StrEnum):
    OBSERVED_BOOK = "OBSERVED_BOOK"
    SIMULATED_SPREAD = "SIMULATED_SPREAD"


class ExecutionMode(StrEnum):
    """Shadow records the call. Paper fills the broker book. Live is the same call with an order."""

    SHADOW = "SHADOW"
    PAPER = "PAPER"
    LIVE = "LIVE"


class ModelReadiness(StrEnum):
    NOT_READY = "MODEL_NOT_READY"
    LOW = "LOW"
    READY = "READY"
